# Generated by Django 4.0.4 on 2022-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=300)),
                ('Password', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=1)),
            ],
        ),
    ]
