# Generated by Django 4.0.4 on 2022-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OcmsApp', '0003_alter_students_gentle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Gentle',
            field=models.CharField(max_length=1),
        ),
    ]
